import {
  Student,
  Class,
  Teacher,
  Subject,
  Holiday,
  Assignment,
  TermAttendance,
  TermResult,
  AttendanceRecord,
  SubjectResult,
} from "@/src/types";

// Teachers
export const teachers: Teacher[] = [
  {
    id: "T001",
    firstName: "John",
    lastName: "Okafor",
    email: "j.okafor@softschool.com",
    phoneNumber: "+234 803 123 4567",
  },
  {
    id: "T002",
    firstName: "Mary",
    lastName: "Adeyemi",
    email: "m.adeyemi@softschool.com",
    phoneNumber: "+234 805 234 5678",
  },
  {
    id: "T003",
    firstName: "David",
    lastName: "Nwosu",
    email: "d.nwosu@softschool.com",
    phoneNumber: "+234 807 345 6789",
  },
  {
    id: "T004",
    firstName: "Grace",
    lastName: "Ibrahim",
    email: "g.ibrahim@softschool.com",
    phoneNumber: "+234 809 456 7890",
  },
  {
    id: "T005",
    firstName: "Samuel",
    lastName: "Eze",
    email: "s.eze@softschool.com",
    phoneNumber: "+234 810 567 8901",
  },
  {
    id: "T006",
    firstName: "Blessing",
    lastName: "Okoro",
    email: "b.okoro@softschool.com",
    phoneNumber: "+234 812 678 9012",
  },
  {
    id: "T007",
    firstName: "Peter",
    lastName: "Ajayi",
    email: "p.ajayi@softschool.com",
    phoneNumber: "+234 813 789 0123",
  },
];

// Class
export const studentClass: Class = {
  id: "C001",
  name: "SS3 Science",
  level: "Senior Secondary 3",
  section: "A",
  classTeacher: teachers[0],
};

// Subjects
export const subjects: Subject[] = [
  {
    id: "S001",
    name: "Mathematics",
    code: "MATH301",
    teacher: teachers[1],
    classId: studentClass.id,
  },
  {
    id: "S002",
    name: "Physics",
    code: "PHY301",
    teacher: teachers[2],
    classId: studentClass.id,
  },
  {
    id: "S003",
    name: "Chemistry",
    code: "CHEM301",
    teacher: teachers[3],
    classId: studentClass.id,
  },
  {
    id: "S004",
    name: "Biology",
    code: "BIO301",
    teacher: teachers[4],
    classId: studentClass.id,
  },
  {
    id: "S005",
    name: "English Language",
    code: "ENG301",
    teacher: teachers[5],
    classId: studentClass.id,
  },
  {
    id: "S006",
    name: "Computer Science",
    code: "CSC301",
    teacher: teachers[6],
    classId: studentClass.id,
  },
  {
    id: "S007",
    name: "Further Mathematics",
    code: "FMATH301",
    teacher: teachers[1],
    classId: studentClass.id,
  },
];

// Current Student
export const currentStudent: Student = {
  id: "STU001",
  firstName: "Chidera",
  lastName: "Nnaji",
  studentId: "SS3/2024/001",
  email: "chidera.nnaji@student.softschool.com",
  classId: studentClass.id,
};

// Holidays
export const holidays: Holiday[] = [
  {
    id: "H001",
    name: "Christmas Break",
    startDate: new Date("2024-12-20"),
    endDate: new Date("2025-01-05"),
    description: "Christmas and New Year holidays",
  },
  {
    id: "H002",
    name: "Mid-Term Break",
    startDate: new Date("2025-02-15"),
    endDate: new Date("2025-02-22"),
    description: "Mid-term break for second term",
  },
  {
    id: "H003",
    name: "Easter Break",
    startDate: new Date("2025-04-10"),
    endDate: new Date("2025-04-20"),
    description: "Easter holidays",
  },
  {
    id: "H004",
    name: "Workers' Day",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-01"),
    description: "Public holiday for Workers' Day",
  },
  {
    id: "H005",
    name: "Democracy Day",
    startDate: new Date("2025-06-12"),
    endDate: new Date("2025-06-12"),
    description: "National Democracy Day celebration",
  },
  {
    id: "H006",
    name: "Summer Break",
    startDate: new Date("2025-07-15"),
    endDate: new Date("2025-09-10"),
    description: "Long vacation - summer holidays",
  },
];

// Assignments
export const assignments: Assignment[] = [
  {
    id: "A001",
    title: "Quadratic Equations Practice",
    courseName: "Mathematics",
    courseCode: "MATH301",
    description: "Solve 20 quadratic equations using different methods",
    dateGiven: new Date("2024-11-01"),
    submissionDate: new Date("2024-11-20"),
    teacherId: teachers[1].id,
    status: "pending",
  },
  {
    id: "A002",
    title: "Laws of Motion Experiment Report",
    courseName: "Physics",
    courseCode: "PHY301",
    description:
      "Write a detailed report on Newton's Laws of Motion experiment",
    dateGiven: new Date("2024-11-05"),
    submissionDate: new Date("2024-11-25"),
    teacherId: teachers[2].id,
    status: "pending",
  },
  {
    id: "A003",
    title: "Organic Chemistry Compounds",
    courseName: "Chemistry",
    courseCode: "CHEM301",
    description: "Identify and name 30 organic compounds",
    dateGiven: new Date("2024-10-28"),
    submissionDate: new Date("2024-11-15"),
    teacherId: teachers[3].id,
    status: "submitted",
  },
  {
    id: "A004",
    title: "Cell Division Process",
    courseName: "Biology",
    courseCode: "BIO301",
    description: "Draw and explain the stages of mitosis and meiosis",
    dateGiven: new Date("2024-11-08"),
    submissionDate: new Date("2024-11-28"),
    teacherId: teachers[4].id,
    status: "pending",
  },
  {
    id: "A005",
    title: "Argumentative Essay on Climate Change",
    courseName: "English Language",
    courseCode: "ENG301",
    description: "Write a 500-word argumentative essay on climate change",
    dateGiven: new Date("2024-10-25"),
    submissionDate: new Date("2024-11-10"),
    teacherId: teachers[5].id,
    status: "overdue",
  },
  {
    id: "A006",
    title: "Data Structures Implementation",
    courseName: "Computer Science",
    courseCode: "CSC301",
    description: "Implement Stack and Queue data structures in Python",
    dateGiven: new Date("2024-11-10"),
    submissionDate: new Date("2024-11-30"),
    teacherId: teachers[6].id,
    status: "pending",
  },
];

// Attendance Records
const attendanceRecords: AttendanceRecord[] = [
  {
    id: "ATT001",
    studentId: currentStudent.id,
    date: new Date("2024-09-02"),
    status: "present",
  },
  {
    id: "ATT002",
    studentId: currentStudent.id,
    date: new Date("2024-09-03"),
    status: "present",
  },
  {
    id: "ATT003",
    studentId: currentStudent.id,
    date: new Date("2024-09-04"),
    status: "absent",
    remarks: "Sick",
  },
  {
    id: "ATT004",
    studentId: currentStudent.id,
    date: new Date("2024-09-05"),
    status: "present",
  },
  {
    id: "ATT005",
    studentId: currentStudent.id,
    date: new Date("2024-09-06"),
    status: "present",
  },
  {
    id: "ATT006",
    studentId: currentStudent.id,
    date: new Date("2024-09-09"),
    status: "late",
  },
  {
    id: "ATT007",
    studentId: currentStudent.id,
    date: new Date("2024-09-10"),
    status: "present",
  },
  // Add more records...
];

// Term Attendance
export const termAttendance: TermAttendance = {
  term: "First Term",
  session: "2024/2025",
  totalDays: 65,
  daysPresent: 58,
  daysAbsent: 3,
  daysLate: 3,
  daysExcused: 1,
  attendancePercentage: 89.2,
  records: attendanceRecords,
};

// Subject Results
const subjectResults: SubjectResult[] = [
  {
    subjectId: "S001",
    subjectName: "Mathematics",
    subjectCode: "MATH301",
    firstCA: 18,
    secondCA: 19,
    exam: 68,
    total: 105,
    grade: "A",
    remarks: "Excellent",
    teacherComment: "Outstanding performance in calculus",
  },
  {
    subjectId: "S002",
    subjectName: "Physics",
    subjectCode: "PHY301",
    firstCA: 17,
    secondCA: 18,
    exam: 65,
    total: 100,
    grade: "A",
    remarks: "Excellent",
    teacherComment: "Very good understanding of concepts",
  },
  {
    subjectId: "S003",
    subjectName: "Chemistry",
    subjectCode: "CHEM301",
    firstCA: 16,
    secondCA: 17,
    exam: 60,
    total: 93,
    grade: "A",
    remarks: "Excellent",
    teacherComment: "Good practical skills",
  },
  {
    subjectId: "S004",
    subjectName: "Biology",
    subjectCode: "BIO301",
    firstCA: 15,
    secondCA: 16,
    exam: 58,
    total: 89,
    grade: "B+",
    remarks: "Very Good",
    teacherComment: "Needs more focus on diagrams",
  },
  {
    subjectId: "S005",
    subjectName: "English Language",
    subjectCode: "ENG301",
    firstCA: 18,
    secondCA: 19,
    exam: 70,
    total: 107,
    grade: "A",
    remarks: "Excellent",
    teacherComment: "Excellent writing skills",
  },
  {
    subjectId: "S006",
    subjectName: "Computer Science",
    subjectCode: "CSC301",
    firstCA: 19,
    secondCA: 20,
    exam: 72,
    total: 111,
    grade: "A",
    remarks: "Excellent",
    teacherComment: "Exceptional programming skills",
  },
  {
    subjectId: "S007",
    subjectName: "Further Mathematics",
    subjectCode: "FMATH301",
    firstCA: 17,
    secondCA: 18,
    exam: 64,
    total: 99,
    grade: "A",
    remarks: "Excellent",
    teacherComment: "Strong analytical abilities",
  },
];

// Term Results (Multiple terms/sessions for selection)
export const termResults: TermResult[] = [
  {
    id: "R001",
    studentId: currentStudent.id,
    term: "First Term",
    session: "2024/2025",
    className: studentClass.name,
    subjects: subjectResults,
    totalScore: 704,
    averageScore: 100.57,
    position: 1,
    totalStudents: 42,
    classTeacherComment:
      "Chidera is an exceptional student with outstanding performance across all subjects. Keep up the excellent work!",
    principalComment: "A brilliant student. Well done!",
    nextTermBegins: new Date("2025-01-06"),
  },
  {
    id: "R002",
    studentId: currentStudent.id,
    term: "Third Term",
    session: "2023/2024",
    className: "SS2 Science A",
    subjects: [
      {
        subjectId: "S001",
        subjectName: "Mathematics",
        subjectCode: "MATH201",
        firstCA: 17,
        secondCA: 18,
        exam: 65,
        total: 100,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S002",
        subjectName: "Physics",
        subjectCode: "PHY201",
        firstCA: 16,
        secondCA: 17,
        exam: 62,
        total: 95,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S003",
        subjectName: "Chemistry",
        subjectCode: "CHEM201",
        firstCA: 16,
        secondCA: 16,
        exam: 60,
        total: 92,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S004",
        subjectName: "Biology",
        subjectCode: "BIO201",
        firstCA: 15,
        secondCA: 16,
        exam: 58,
        total: 89,
        grade: "B+",
        remarks: "Very Good",
      },
      {
        subjectId: "S005",
        subjectName: "English Language",
        subjectCode: "ENG201",
        firstCA: 17,
        secondCA: 18,
        exam: 67,
        total: 102,
        grade: "A",
        remarks: "Excellent",
      },
    ],
    totalScore: 478,
    averageScore: 95.6,
    position: 2,
    totalStudents: 40,
    classTeacherComment:
      "Excellent performance. Promotion to SS3 is well deserved.",
    principalComment: "Keep striving for excellence!",
    nextTermBegins: new Date("2024-09-02"),
  },
  {
    id: "R003",
    studentId: currentStudent.id,
    term: "Second Term",
    session: "2023/2024",
    className: "SS2 Science A",
    subjects: [
      {
        subjectId: "S001",
        subjectName: "Mathematics",
        subjectCode: "MATH201",
        firstCA: 18,
        secondCA: 19,
        exam: 66,
        total: 103,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S002",
        subjectName: "Physics",
        subjectCode: "PHY201",
        firstCA: 17,
        secondCA: 18,
        exam: 64,
        total: 99,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S003",
        subjectName: "Chemistry",
        subjectCode: "CHEM201",
        firstCA: 17,
        secondCA: 17,
        exam: 61,
        total: 95,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S004",
        subjectName: "Biology",
        subjectCode: "BIO201",
        firstCA: 16,
        secondCA: 17,
        exam: 59,
        total: 92,
        grade: "A",
        remarks: "Excellent",
      },
      {
        subjectId: "S005",
        subjectName: "English Language",
        subjectCode: "ENG201",
        firstCA: 18,
        secondCA: 19,
        exam: 68,
        total: 105,
        grade: "A",
        remarks: "Excellent",
      },
    ],
    totalScore: 494,
    averageScore: 98.8,
    position: 1,
    totalStudents: 40,
    classTeacherComment: "Exceptional student with consistent excellence.",
    principalComment: "Outstanding performance!",
  },
];
